### ISSUE TITLE
Add missing dependecies

### ISSUE THREAD

**Issue by sugatoray** [conda-forge/py7zr-feedstock#15]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I was working on another conda-forge recipe, when I the build failed because of some pip-check errors. It appears that the following two dependencies are necessary for `py7zr`.

```yaml
requirements:
  run:
	...
	# pyppmd and zipfile-deflate constraints are necessary for py7zr
    - pyppmd >=0.17.0,<0.18.0
    - zipfile-deflate64 >=0.2.0
```

Please update the conda-forge package dependencies accordingly.

Refer to: https://github.com/conda-forge/staged-recipes/pull/18423#discussion_r833280222

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```
